# [START app_yaml]
runtime: nodejs14

env_variables:
  PORT: 8080
  NODE_ENV: stage
  DB_HOST: backyard-stage-db-do-user-6012695-0.b.db.ondigitalocean.com
  DB_USER: byf
  DB_PASS: AVNS_lM25mnEfowo3P0b7CEb
  DB_NAME: friends
  DB_PORT: 25060
  JWT_SECRET: production_secret
  S3_ENDPOINT: sfo3.digitaloceanspaces.com
  DO_BUCKET: byf-images
  DO_ACCESS_KEY_ID: DO00NDV9Z7BP6DURA2FF
  DO_SECRET_ACCESS_KEY: 9FN+PGiWP53/9dYgi3L/Qxr26ahcjQhX2c4x5lWQi7s
# [END app_yaml]
