services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_DATABASE=friends
      - MYSQL_USER=byf
      - MYSQL_PASSWORD=<temp>
      - MYSQL_RANDOM_ROOT_PASSWORD=123
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
      - ./avys/config/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
secrets:
  npmrc:
    file: /Users/andrewmaclean/.npmrc
