services:
  couloirs:
    container_name: couloirs
    image: couloirs
    build:
      context: ./couloirs
      dockerfile: Dockerfile.development
      secrets:
        - npmrc
    restart: on-failure
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=byf
      - DB_PASS=<temp>
      - MONGO_PASS=<temp>
      - DB_NAME=friends
      - DB_PORT=3306
      - FILE_STORAGE=/home/app/public/images
      - JWT_SECRET=secret
    ports:
      - '4000:4000'
    volumes:
      - ./couloirs:/home/app
      - /home/app/node_modules
  rivers:
    container_name: rivers
    command: npm run docker
    image: rivers
    build:
      context: ./rivers
      dockerfile: Dockerfile.development
      secrets:
        - npmrc
    restart: on-failure
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=byf
      - DB_PASS=<temp>
      - MONGO_PASS=<temp>
      - DB_NAME=friends
      - DB_PORT=3306
      - FILE_STORAGE_PATH=/home/app/public/images
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiYW1hY2xlYW4iLCJhIjoiY2wydzM2YjB2MGh4dzNqb2FpeTg2bmo4dSJ9.KSDbOciqbYDn5eA4SHNOZg
      - NODEMAILER_APP_PASSWORD=vtmrorarxqkhfcjc
      - JWT_SECRET=secret
    volumes:
      - files:/home/app/public/images
      - ./rivers:/home/app
      - /home/app/node_modules
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_DATABASE=friends
      - MYSQL_USER=byf
      - MYSQL_PASSWORD=<temp>
      - MYSQL_RANDOM_ROOT_PASSWORD=123
    ports:
      - '3300:3306'
    volumes:
      - data:/var/lib/mysql
      - ./rivers/Config/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
  files:
secrets:
  npmrc:
    file: /Users/andrewmaclean/.npmrc
