services:
  couloirs:
    container_name: couloirs
    image: couloirs
    build: 
      context: ./couloirs
      dockerfile: Dockerfile.development
    restart: on-failure
    ports:
      - '4000:4000'
    volumes:
      - ./couloirs:/home/app
      - /home/app/node_modules
  rivers:
    container_name: rivers
    image: rivers
    build: 
      context: ./rivers
      dockerfile: Dockerfile.development
    restart: on-failure
    ports:
      - '5000:5000'
    volumes:
      - ./rivers:/home/app
      - /home/app/node_modules
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: on-failure
    environment:
      - MYSQL_DATABASE=friends
      - MYSQL_USER=byf
      - MYSQL_PASSWORD=backyard
      - MYSQL_RANDOM_ROOT_PASSWORD=123
    ports:
      - '3300:3306'
    volumes:
      - data:/var/lib/mysql
      - ./rivers/Config/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
