services:
  avys:
    container_name: avys
    image: amacleanjs/sunday-morning:latest
    restart: unless-stopped
    environment:
      - PORT=443
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=byf
      - DB_PASS=backyard
      - DB_NAME=friends
      - MONGO_PASS=backyard
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiYW1hY2xlYW4iLCJhIjoiY2wydzM2YjB2MGh4dzNqb2FpeTg2bmo4dSJ9.KSDbOciqbYDn5eA4SHNOZg
      - NODEMAILER_APP_PASSWORD=vtmrorarxqkhfcjc
      - JWT_SECRET=jB2MGh4dzN
      - FILE_STORAGE_PATH=/home/app/public/images
    ports:
      - '443:443'
    volumes:
      - /home/images:/home/app/public/images
      - /home/dockerConfig/certbot/etc/:/etc/letsencrypt
      - /home/dockerConfig/certbot/var/:/var/lib/letsencrypt
    networks:
      - sundaypeak
  rivers:
    container_name: rivers
    image: amacleanjs/sunday-service:latest
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=byf
      - DB_PASS=backyard
      - DB_NAME=friends
      - MONGO_PASS=backyard
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiYW1hY2xlYW4iLCJhIjoiY2wydzM2YjB2MGh4dzNqb2FpeTg2bmo4dSJ9.KSDbOciqbYDn5eA4SHNOZg
      - NODEMAILER_APP_PASSWORD=vtmrorarxqkhfcjc
      - JWT_SECRET=jB2MGh4dzN
      - FILE_STORAGE_PATH=/home/app/public/images
    ports:
      - '5000:5000'
    volumes:
      - /home/images:/home/app/public/images
    networks:
      - sundaypeak
  couloirs:
    container_name: couloirs
    image: amacleanjs/sunday-communion:latest
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=byf
      - DB_PASS=backyard
      - DB_NAME=friends
      - MONGO_PASS=backyard
      - JWT_SECRET=jB2MGh4dzN
      - FILE_STORAGE_PATH=/home/app/public/images
    volumes:
      - /home/images:/home/app/public/images
    networks:
      - sundaypeak
    ports:
      - '4000:4000'
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/dockerConfig/certbot/etc/:/etc/letsencrypt
      - /home/dockerConfig/certbot/var/:/var/lib/letsencrypt
      - /home/dockerConfig/certbot/files:/var/www/html
      - /home/dockerConfig/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sundaypeak
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/dockerConfig/certbot/etc:/etc/letsencrypt
      - /home/dockerConfig/certbot/var:/var/lib/letsencrypt
      - /home/dockerConfig/certbot/files:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email andrew@sundaypeak.com --agree-tos --no-eff-email --force-renewal -d api.sundaypeak.com
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql
    ports:
      - '3300:3306'
    volumes:
      - /home/data:/var/lib/mysql
      - /home/initialization/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sundaypeak
    environment:
      - MYSQL_USER=byf
      - MYSQL_PASSWORD=backyard
      - MYSQL_DATABASE=friends
      - MYSQL_RANDOM_ROOT_PASSWORD=123
networks:
  sundaypeak:
    driver: bridge

