name: Publish Rivers Directory

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: martinbeentjes/npm-get-version-action@v1.3.1
        name: get-package-version
        id: package-version
        with:
          path: ./avys

      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./avys
        run: docker build --platform linux/amd64 -t amacleanjs/sunday-morning:${{ steps.package-version.outputs.current-version}} -t amacleanjs/sunday-morning:latest --secret id=npmrc,src=$HOME/.npmrc .
